In [11]:
from pathlib import Path
import os
import datetime as dt
import pandas as pd

### Path and dataframe dictionaries

In [12]:

from csv import QUOTE_NONE


paths = dict()
for csv in (Path(os.path.abspath("")).parents[1] / "data" / "schoolshooters").rglob("data.csv"):
    paths[csv.parents[0].name] = csv

dfs = dict()
for key, value in paths.items():
    dfs[key] = pd.read_csv(value, encoding="utf-8", delimiter="‎", engine="python", quoting=QUOTE_NONE)

dfs

{'Seung_Hui_Cho':     date                                               text
 0    NaN  Oh the happiness I could have had mingling amo...
 1    NaN  Only if you could be the victim of your repreh...
 2    NaN  For every action, there is an equal and opposi...
 3    NaN  All the shit you’ve given me, right back at yo...
 4    NaN  You had a hundred billion chances and ways to ...
 5    NaN  Congratulations. You have succeeded in extingu...
 6    NaN  To you sadistic snobs, I may be nothing but a ...
 7    NaN  You may stand steadfast on the battlefield of ...
 8    NaN      Seer of Veracity. Seal of the Anti-Terrorist.
 9    NaN  Number of the Anti-Terrorist. You wanna rape u...
 10   NaN  By destroying we create. We create the feeling...
 11   NaN  It’s grand for you to fuck us 24/7 for fun, bu...
 12   NaN  We have no sympathy in killing humans who have...
 13   NaN  Now that the slate has been cleaned and you ha...
 14   NaN  The blood of the Innocents should never be she...
 15   NaN  will not quench the avenging phoenix that you ...
 16   NaN  As the time approached, I wished for a last mi...
 17   NaN  If you have a single milligram of conscience, ...
 18   NaN  All of you who have ever been fucked by these ...
 19   NaN                          Let the revolution begin!
 20   NaN  Die you Descendants of Satan! Fuck you, and di...
 21   NaN  Are you happy now that you have destroyed my l...,
 'Thomas_Michael_Lane':          date                                               text
 0  2011-12-30  In a time long since, a time of repent, The Re...
 1  2012-01-20  much obliged to all who "liked" this. Wrote it...,
 'Jon_Romano':          date                                               text
 0  2004-02-09  I’m just too afraid of the future. I could do ...
 1  2004-01-24  Rachel, It’s January 24, 2004 and you’re leavi...,
 'Adam_Lanza':            date                                               text
 0    2010-07-05  My favorite two are Bloody Wednesday (It was s...
 1    2010-07-06  I’m probably the only one here who would like ...
 2    2010-07-06  I had the same reaction. I was wondering “Wher...
 3    2010-10-30  I've been considering posting a topic sort of ...
 4    2010-10-31             That water better had not be flavored!
 ..          ...                                                ...
 211  2012-02-24  That's weird. I know that the Latest Activity ...
 212  2012-02-24  I was recently thinking about how hostage situ...
 213  2012-02-26  "I hate how life-apologists say (or rather, th...
 214  2012-02-28  "http://www.youtube.com/watch?v=De-tIflr4E0&t=...
 215  2012-02-28  "I could go in a hundred different ways with t...

 [216 rows x 2 columns],
 'Kip_Kinkel':    date                                               text
 0   NaN  I sit here all alone. I am always alone. I don...
 1   NaN           You all make me sick. I wish I was dead.
 2   NaN                       Killers start sad and crazy.
 3   NaN  I will hunt you down and put a hole in your he...
 4   NaN  No, I don’t believe in love at first sight bec...
 5   NaN  I have just killed my parents! I don’t know wh...
 6   NaN  I have spent days trying to figure out what I ...
 7   NaN  But you know me, I loathe all of them. I am no...,
 'Jeffrey_Weise':           date                                               text
 0   2004-12-14  Out with the old, and in with the new. As I si...
 1   2004-01-04  The instrument of my resurrection was supposed...
 2   2005-01-27  So fucking naive man, so fucking naive. Always...
 3          NaN  Thoughts of a Dreamer. Liberate your mind, bit...
 4          NaN  Nothin' but a native American teenage-stoner-i...
 5   2004-03-19  Hello all, My name is Jeff Weise, a Native Ame...
 6   2004-03-19  Thank you. What brings me to the forum? Well, ...
 7   2004-03-25  Once I commit myself to something, I stay unti...
 8   2004-04-19  Hmn, after a recent discussion with some misin...
 9   2004-05-26  You encounter a lot of hostility when you clai...
 10  2004-07-19  Apparently a lot of people have never heard of...
 11  2004-07-20  Anymore Native American NS's? Not right now, t...,
 'Eric_Harris':            date                                               text
 0    1998-04-10  I hate the fucking world, too much god damn fu...
 1    1998-04-12  As I said before, self-awareness is a wonderfu...
 2    1998-04-21  Ever wonder why we go to school? Besides getti...
 3    1998-05-06  The human race sucks. Human nature is smothere...
 4    1998-05-09  It has been confirmed, after getting my yearbo...
 ..          ...                                                ...
 139         NaN  I hate this kind of fuckin music. Goddamn whit...
 140         NaN                                        Supa Nigga!
 141         NaN  Philosophy: My belief is that if I say somethi...
 142         NaN  f its residents. Fucking people with their ric...
 143         NaN  Wie gehts. Well all you people out there can j...

 [144 rows x 2 columns],
 'Sebastian_Bosse':           date                                               text
 0   2006-08-10  Of all the lives in this world, apparently min...
 1   2006-08-13  Shit! I feel as if I’m about to croak! My hear...
 2   2006-08-19  Imagine you are in your old school, imagine th...
 3   2006-08-25  Soon we are on our way to OP Black Ede, if I c...
 4   2006-09-14  School shooting in Montreal! Quote n24: “. . ....
 5   2006-09-18  We don’t live in a democracy! We are well on o...
 6   2006-09-26  ERIC HARRIS Probably the most reasonable boy t...
 7   2006-10-18  It doesn’t matter what you do in your life, ev...
 8   2006-11-06  Right now I’m holding a 12 Gauge Alarm Patrone...
 9   2006-11-13  Today I passed the point of no return. I shot ...
 10  2006-11-16  I just gave S!lent my G3SAS with all its stuff...
 11  2006-11-17  In 3 days it’s all over. People will be lying ...
 12  2006-11-19  This is the last evening I will ever see. I sh...
 13  2006-11-20                                         That’s it!,
 'Charles Whitman':          date                                               text
 0  1966-07-31  I don’t quite understand what it is that compe...
 1  1966-08-01  THOUGHTS TO START THE DAY READ AND THINK ABOUT...,
 'Robert_Butler_jr':          date                                               text
 0  2011-01-05  Everybody that used to know me I’m sry but Oma...,
 'Luke_Woodham':          date                                               text
 0         NaN  If I could spend a day as Mrs. Neal, I would b...
 1         NaN  I’ve never really done anything that bad, so I...
 2     1997-04  . . . I am the hatred in every man’s heart! I ...
 3  1997-04-14  On Saturday of last week, I made my first kill...
 4  1997-06-03  This night (June 3, 1997) is a monumentatious ...
 5         NaN  I am not insane! I am angry. This world has sh...
 6         NaN  I, Luke Woodham, being of sound mind and body,...
 7         NaN  It was not a cry for attention, it was not a c...,
 'Dylan_Klebold':           date                                               text
 0          NaN  Fact: People are so unaware. . . . well, Ignor...
 1   1997-03-31  <<–Vodka–>> Life-existence EL THOUGHTZOS Ah ye...
 2   1997-04-15  <<–VoDkA–>> poetry my way Da ThoughtZ Jeah Wel...
 3         1997  <<–VoDkA–>> 5-2 my thoughtz shit Thoughtz Yo ....
 4   1997-07-23  A changing time <<–VoDkA–>>’s Thoughts The Sit...
 5          NaN  My 1st Love???? OH my God . . . I am almost su...
 6   1997-09-05  <<–VoDkA–>> Life, sucks My thoughts Oooh god I...
 7          NaN  Ignorance is bliss happiness is ambition desol...
 8          NaN  Goodbye, sorry to everyone . . . I just can’t ...
 9          NaN  me is a god, a god of sadness exiled to this e...
 10  1997-10-14  Fuck that → Dylan Klebold Me fuck thoughtz Me....
 11         NaN  Awareness signs the warrant for suffering. Why...
 12  1997-11-03  this fuck all Thoughts Farther and farther dis...
 13  1998-01-02  Beeerr . . . Man I don’t know what’s up lately...
 14         NaN  Everything No, everything No, everything No, e...
 15  1998-02-02  I the everything Existence . . . to understand...
 16  1998-06-08  Our halcyon I LOVE !! I love her to infinince....
 17  1998-06-10  me I think don’t care (?) Forever fate, up & d...
 18  1999-01-20  Dylan This Shit This shit again. Back at writi...
 19         NaN  The humanity of here & now clouds all that I s...
 20         NaN  1. One day, one is the beginning, the end. Hah...
 21         NaN  Dylan Klebold will WILL Ok, this is my will. T...
 22         NaN  Knee deep in the dead. REB! Hooooly shit . . ....
 23         NaN  HELL ON EARTH Ahhhh, my favorite book. We, the...
 24         NaN  Infernal Sky Man. . . . let’s sum up junior ye...
 25         NaN  My Quotes!!! — Dead people are the best compan...
 26         NaN  Endgame (?. . .) Last written book, more to co...,
 'William_Atchison':            date                                               text
 0           NaN  HOBBIES: Benzocaine, antidepressants, computer...
 1    2009-09-11  1.I was immune to getting hurt/killed/infected...
 2    2009-09-11  I mean terrorist attacks happen all the time. ...
 3    2009-09-13  As a god, it would be my responsibility not to...
 4    2009-09-13  I am going to grab a knife and shove it in the...
 ..          ...                                                ...
 264  2017-12-04  Once I really am in power, my first and foremo...
 265  2017-12-05  Remember kids: If you plan on killing people d...
 266  2017-12-06                                 Praise be to allah
 267  2017-12-07  If things go according to plan, today would be...
 268  2017-12-07                                               Die.

 [269 rows x 2 columns],
 'Evan_Ramsey':    date                                               text
 0   NaN  I have thought to myself, what kind of damage ...
 1   NaN  Hey Every body!! I feel rejected, rejected, no...,
 'Alvaro_Castillo':          date                                               text
 0         NaN  - No cuss words or profanity is used. I do not...
 1  2006-03-29  Dear Journal, I am going to do it! I have been...
 2         NaN                                  - Shotgun Reciept
 3         NaN  Alvaro Castillo Rest In Peace!!! Born: Novembe...
 4  2006-06-12  Dear Journal, Well, today I gave Arlene a comp...
 5  2006-08-08  Dear Journal, I will buy black cargo pants and...
 6  2006-08-23  Dear Journal, In one week, I will finally be d...
 7  2006-08-30  Dear Journal, Today is the big day for Operati...,
 'Jose_Reyes':    date                                               text
 0   NaN  Dear mom and dad I'm sorry about all this is b...
 1   NaN  Dear teachers and students today is the day wh...,
 'Karl_Pierson':           date                                               text
 0   2013-09-17  enter project saguntum, a 10 year subconscious...
 1   2013-09-22  I am filled with hate, I love it. The serotoni...
 2   2013-09-30  I feel like a bomb. My head has happy, anger a...
 3   2013-10-01  Saguntum is the project to shoot up (and maybe...
 4   2013-10-03  Since day 1, my job has been to conspire to sh...
 5   2013-10-11  I had a shrink appointment at 4, which was a m...
 6   2013-10-15  I had an interesting idea today. In first hour...
 7   2013-10-26  the 13th of December is a great date, as the 3...
 8   2013-11-06  I am estatic right now. That December 13 date ...
 9   2013-11-24  It's weird going through life knowing that in ...
 10  2013-11-26  I can't believe in a fortnight I'll be dead. I...
 11  2013-12-08  it was productive weekend. I bought my Stevens...
 12  2013-12-12  I went to Cabela's and I bought a sling, ammo ...
 13  2013-12-13  today is going to be fun. I dropped off at sch...
 14  2013-12-13  The plan: 5th hours starts at 1214. I would wa...,
 'Kimveer_Gill':            date                                               text
 0    2005-12-03  Winter - Winter approaches from all  sides. It...
 1    2005-12-23  Vengeance is coming - It will be a  quiet and ...
 2    2005-12-27  Lacuna Coil - Listening to Lacuna  Coil. She f...
 3    2005-12-31  Megadeth - That's a cool name for aband. "Mega...
 4    2006-01-04  He walks alone - He opened the door,  walked d...
 ..          ...                                                ...
 110  2006-09-13  - Hey girls, if you're feeling down,  buy a ki...
 111  2006-09-13  Frezzies - Freezies rock  I'm eatting a purple...
 112  2006-09-13  It's me :) - German Metal  Yaaaaaaaaaaaaaa  As...
 113  2006-09-13  Wednessday the 13th - Woke up 30  minutes ago....
 114  2006-09-13  - Whiskey in the morning,  mmmmmm, mmmmmmmmm, ...

 [115 rows x 2 columns],
 'Gang_Lu':    date                                               text
 0   NaN  STATEMENT by Mr. Lu Gang, Ph.D. My this life i...,
 'Randy_Stair':    date                                               text
 0   NaN  When I was a little kid I always dreamed of be...}

### Read data and append date columns

In [13]:
def append_date_columns(dataframe: pd.DataFrame):
    df = dataframe.copy()
    date_dict = { "year": [], "month": [], "day": [] }
    for date in df["date"].convert_dtypes():
        year, month, day = [None, None, None] if type(date) == pd._libs.missing.NAType else (date.split("-") + 3 * [None])[:3]
        date_dict["year"].append(year)
        date_dict["month"].append(month)
        date_dict["day"].append(day)
    for key in date_dict.keys():
        df[key] = date_dict[key]
    return df

# Append year, month and day columns. 
# This method insert None for undefined values

df = append_date_columns(dfs["Alvaro_Castillo"])
df

,date,text,year,month,day
0,NaN,- No cuss words or profanity is used. I do not...,None,None,None
1,2006-03-29,"Dear Journal, I am going to do it! I have been...",2006,03,29
2,NaN,- Shotgun Reciept,None,None,None
3,NaN,Alvaro Castillo Rest In Peace!!! Born: Novembe...,None,None,None
4,2006-06-12,"Dear Journal, Well, today I gave Arlene a comp...",2006,06,12
5,2006-08-08,"Dear Journal, I will buy black cargo pants and...",2006,08,08
6,2006-08-23,"Dear Journal, In one week, I will finally be d...",2006,08,23
7,2006-08-30,"Dear Journal, Today is the big day for Operati...",2006,08,30

### Concat all into one big dataframe

In [14]:
list_of_names = list(dfs.keys())
list_of_dfs = [append_date_columns(df).assign(name=list_of_names[index].replace("_", " ")) for index, df in enumerate(dfs.values())]
df = pd.concat(list_of_dfs).reset_index()
df

,index,date,text,year,month,day,name
0,0,NaN,Oh the happiness I could have had mingling amo...,None,None,None,Seung Hui Cho
1,1,NaN,Only if you could be the victim of your repreh...,None,None,None,Seung Hui Cho
2,2,NaN,"For every action, there is an equal and opposi...",None,None,None,Seung Hui Cho
3,3,NaN,"All the shit you’ve given me, right back at yo...",None,None,None,Seung Hui Cho
4,4,NaN,You had a hundred billion chances and ways to ...,None,None,None,Seung Hui Cho
...,...,...,...,...,...,...,...
866,112,2006-09-13,It's me :) - German Metal Yaaaaaaaaaaaaaa As...,2006,09,13,Kimveer Gill
867,113,2006-09-13,Wednessday the 13th - Woke up 30 minutes ago....,2006,09,13,Kimveer Gill
868,114,2006-09-13,"- Whiskey in the morning, mmmmmm, mmmmmmmmm, ...",2006,09,13,Kimveer Gill
869,0,NaN,"STATEMENT by Mr. Lu Gang, Ph.D. My this life i...",None,None,None,Gang Lu
870,0,NaN,When I was a little kid I always dreamed of be...,None,None,None,Randy Stair

### Some statistics

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 871 entries, 0 to 870
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   871 non-null    int64
 1   date    685 non-null    object
 2   text    871 non-null    object
 3   year    685 non-null    object
 4   month   639 non-null    object
 5   day     624 non-null    object
 6   name    871 non-null    object
dtypes: int64(1), object(6)
memory usage: 47.8+ KB

In [16]:
df.nunique()

index    269
date     406
text     867
year      16
month     12
day       31
name      20
dtype: int64

### Find duplicate entries

In [17]:
texts = df["text"]
df[texts.isin(texts[texts.duplicated()])].sort_values("text")

     index date          text  year month   day         name
321     59  NaN  Ich bin Gott  None  None  None  Eric Harris
322     60  NaN  Ich bin Gott  None  None  None  Eric Harris
325     63  NaN  Ich bin Gott  None  None  None  Eric Harris
332     70  NaN  Ich bin Gott  None  None  None  Eric Harris
338     76  NaN  Ich bin Gott  None  None  None  Eric Harris