In [1]:
from pathlib import Path
import os
import datetime as dt
import pandas as pd

### Path and dataframe dictionaries

In [2]:

paths = dict()
for csv in (Path(os.path.abspath("")).parents[1] / "schoolshootersinfo").rglob("*.csv"):
    paths[csv.parents[0].name] = csv

dfs = dict()
for key, value in paths.items():
    dfs[key] = pd.read_csv(value, delimiter="‎ ", engine='python', encoding="utf-8")

dfs
dfs["Seung_Hui_Cho"]

    date                                               text
0    NaN  Oh the happiness I could have had mingling amo...
1    NaN  Only if you could be the victim of your repreh...
2    NaN  For every action, there is an equal and opposi...
3    NaN  All the shit you’ve given me, right back at yo...
4    NaN  You had a hundred billion chances and ways to ...
5    NaN  Congratulations. You have succeeded in extingu...
6    NaN  To you sadistic snobs, I may be nothing but a ...
7    NaN  You may stand steadfast on the battlefield of ...
8    NaN      Seer of Veracity. Seal of the Anti-Terrorist.
9    NaN  Number of the Anti-Terrorist. You wanna rape u...
10   NaN  By destroying we create. We create the feeling...
11   NaN  It’s grand for you to fuck us 24/7 for fun, bu...
12   NaN  We have no sympathy in killing humans who have...
13   NaN  Now that the slate has been cleaned and you ha...
14   NaN  The blood of the Innocents should never be she...
15   NaN  will not quench the avenging phoenix that you ...
16   NaN  As the time approached, I wished for a last mi...
17   NaN  If you have a single milligram of conscience, ...
18   NaN  All of you who have ever been fucked by these ...
19   NaN                          Let the revolution begin!
20   NaN  Die you Descendants of Satan! Fuck you, and di...
21   NaN  Are you happy now that you have destroyed my l...

### Read data and append date columns

In [14]:
def append_date_columns(dataframe: pd.DataFrame):
    df = dataframe.copy()
    date_dict = { "year": [], "month": [], "day": [] }
    for date in df["date"].convert_dtypes():
        year, month, day = [None, None, None] if type(date) == pd._libs.missing.NAType else (date.split("-") + 3 * [None])[:3]
        date_dict["year"].append(year)
        date_dict["month"].append(month)
        date_dict["day"].append(day)
    for key in date_dict.keys():
        df[key] = date_dict[key]
    return df

# Append year, month and day columns. 
# This method insert None for undefined values

df = append_date_columns(dfs["Alvaro_Castillo"])
df

,date,text,year,month,day
0,NaN,- No cuss words or profanity is used. I do not...,None,None,None
1,2006-03-29,"Dear Journal, I am going to do it! I have been...",2006,03,29
2,NaN,- Shotgun Reciept,None,None,None
3,NaN,Alvaro Castillo Rest In Peace!!! Born: Novembe...,None,None,None
4,2006-06-12,"Dear Journal, Well, today I gave Arlene a comp...",2006,06,12
5,2006-08-08,"Dear Journal, I will buy black cargo pants and...",2006,08,08
6,2006-08-23,"Dear Journal, In one week, I will finally be d...",2006,08,23
7,2006-08-30,"Dear Journal, Today is the big day for Operati...",2006,08,30

### Concat all into one big dataframe

In [15]:
list_of_names = list(dfs.keys())
list_of_dfs = [append_date_columns(df).assign(Name=list_of_names[index].replace("_", " ")) for index, df in enumerate(dfs.values())]
df = pd.concat(list_of_dfs).reset_index()
df

,index,date,text,year,month,day,Name
0,0,NaN,Oh the happiness I could have had mingling amo...,None,None,None,Seung Hui Cho
1,1,NaN,Only if you could be the victim of your repreh...,None,None,None,Seung Hui Cho
2,2,NaN,"For every action, there is an equal and opposi...",None,None,None,Seung Hui Cho
3,3,NaN,"All the shit you’ve given me, right back at yo...",None,None,None,Seung Hui Cho
4,4,NaN,You had a hundred billion chances and ways to ...,None,None,None,Seung Hui Cho
...,...,...,...,...,...,...,...
632,112,2006-09-13,It's me :) - German Metal Yaaaaaaaaaaaaaa As...,2006,09,13,Kimveer Gill
633,113,2006-09-13,Wednessday the 13th - Woke up 30 minutes ago....,2006,09,13,Kimveer Gill
634,114,2006-09-13,"- Whiskey in the morning, mmmmmm, mmmmmmmmm, ...",2006,09,13,Kimveer Gill
635,0,NaN,When I was a little kid I always dreamed of be...,None,None,None,Randy Stair
636,0,NaN,ATTACK INFORMATION Event: Jokela High School M...,None,None,None,Pekka Eric Auvinen

### Some statistics

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 637 entries, 0 to 636
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   637 non-null    int64
 1   date    456 non-null    object
 2   text    637 non-null    object
 3   year    456 non-null    object
 4   month   410 non-null    object
 5   day     395 non-null    object
 6   Name    637 non-null    object
dtypes: int64(1), object(6)
memory usage: 35.0+ KB

In [17]:
df.nunique()

index    269
date     300
text     633
year      14
month     12
day       31
Name      17
dtype: int64