In [65]:
from pathlib import Path
import os
import datetime as dt
import pandas as pd

### Path and dataframe dictionaries

In [66]:

paths = dict()
for csv in (Path(os.path.abspath("")).parents[1] / "schoolshootersinfo").rglob("*.csv"):
    paths[csv.parents[0].name] = csv

dfs = dict()
for key, value in paths.items():
    dfs[key] = pd.read_csv(value, delimiter="‎ ", engine='python', encoding="utf-8")

dfs

{'Cho':     date                                               text
 0    NaN  Oh the happiness I could have had mingling amo...
 1    NaN  Only if you could be the victim of your repreh...
 2    NaN  For every action, there is an equal and opposi...
 3    NaN  All the shit you’ve given me, right back at yo...
 4    NaN  You had a hundred billion chances and ways to ...
 5    NaN  Congratulations. You have succeeded in extingu...
 6    NaN  To you sadistic snobs, I may be nothing but a ...
 7    NaN  You may stand steadfast on the battlefield of ...
 8    NaN      Seer of Veracity. Seal of the Anti-Terrorist.
 9    NaN  Number of the Anti-Terrorist. [photograph of h...
 10   NaN  By destroying we create. We create the feeling...
 11   NaN  It’s grand for you to fuck us 24/7 for fun, bu...
 12   NaN  We have no sympathy in killing humans who have...
 13   NaN  Now that the slate has been cleaned and you ha...
 14   NaN  The blood of the Innocents should never be she...
 15   NaN  will not quench the avenging phoenix that you ...
 16   NaN  As the time approached, I wished for a last mi...
 17   NaN  If you have a single milligram of conscience, ...
 18   NaN  All of you who have ever been fucked by these ...
 19   NaN                          Let the revolution begin!
 20   NaN  Die you Descendants of Satan! Fuck you, and di...
 21   NaN  Are you happy now that you have destroyed my l...,
 'Sebastian_Bosse':           date                                               text
 0   2006-08-10  Of all the lives in this world, apparently min...
 1   2006-08-13  Shit! I feel as if I’m about to croak! My hear...
 2   2006-08-19  Imagine you are in your old school, imagine th...
 3   2006-08-25  Soon we are on our way to OP Black Ede, if I c...
 4   2006-09-14  School shooting in Montreal! Quote n24: “. . ....
 5   2006-09-18  We don’t live in a democracy! We are well on o...
 6   2006-09-26  ERIC HARRIS Probably the most reasonable boy t...
 7   2006-10-18  It doesn’t matter what you do in your life, ev...
 8   2006-11-06  Right now I’m holding a 12 Gauge Alarm Patrone...
 9   2006-11-13  Today I passed the point of no return. I shot ...
 10  2006-11-16  I just gave S!lent my G3SAS with all its stuff...
 11  2006-11-17  In 3 days it’s all over. People will be lying ...
 12  2006-11-19  This is the last evening I will ever see. I sh...
 13  2006-11-20                                         That’s it!,
 'Dylan_Klebold':   date  text
 0    ‎   NaN
 1    ‎   NaN
 2    ‎   NaN
 3    ‎   NaN,
 'William_Atchison':            date                                               text
 0           NaN  HOBBIES: Benzocaine, antidepressants, computer...
 1    2009-09-11  1.I was immune to getting hurt/killed/infected...
 2    2009-09-11  I mean terrorist attacks happen all the time. ...
 3    2009-09-13  As a god, it would be my responsibility not to...
 4    2009-09-13  I am going to grab a knife and shove it in the...
 ..          ...                                                ...
 264  2017-12-04  Once I really am in power, my first and foremo...
 265  2017-12-05  Remember kids: If you plan on killing people d...
 266  2017-12-06                                 Praise be to allah
 267  2017-12-07  If things go according to plan, today would be...
 268  2017-12-07                                               Die.

 [269 rows x 2 columns],
 'Fabrikant':    date                                               text
 0   NaN  On the one hand, I had a good formal defense b...,
 'Evan_Ramsey':    date                                               text
 0   NaN  I have thought to myself, what kind of damage ...
 1   NaN  Hey Every body!! I feel rejected, rejected, no...,
 'Karl_Pierson':           date                                               text
 0   2013-09-17  enter project saguntum, a 10 year subconscious...
 1   2013-09-22  I am filled with hate, I love it. The serotoni...
 2   2013-09-30  I feel like a bomb. My head has happy, anger a...
 3   2013-10-01  Saguntum is the project to shoot up (and maybe...
 4   2013-10-03  Since day 1, my job has been to conspire to sh...
 5   2013-10-11  I had a shrink appointment at 4, which was a m...
 6   2013-10-15  I had an interesting idea today. In first hour...
 7   2013-10-26  the 13th of December is a great date, as the 3...
 8   2013-11-06  I am estatic right now. That December 13 date ...
 9   2013-11-24  It's weird going through life knowing that in ...
 10  2013-11-26  I can't believe in a fortnight I'll be dead. I...
 11  2013-12-08  it was productive weekend. I bought my Stevens...
 12  2013-12-12  I went to Cabela's and I bought a sling, ammo ...
 13  2013-12-13  today is going to be fun. I dropped off at sch...
 14  2013-12-13  The plan: 5th hours starts at 1214. I would wa...,
 'Kimveer_Gill':            date                                               text
 0    2005-12-03  Winter - Winter approaches from all  sides. It...
 1    2005-12-23  Vengeance is coming - It will be a  quiet and ...
 2    2005-12-27  Lacuna Coil - Listening to Lacuna  Coil. She f...
 3    2005-12-31  Megadeth - That's a cool name for aband. "Mega...
 4    2006-01-04  He walks alone - He opened the door,  walked d...
 ..          ...                                                ...
 110  2006-09-13  - Hey girls, if you're feeling down,  buy a ki...
 111  2006-09-13  Frezzies - Freezies rock  I'm eatting a purple...
 112  2006-09-13  It's me :) - German Metal  Yaaaaaaaaaaaaaa  As...
 113  2006-09-13  Wednessday the 13th - Woke up 30  minutes ago....
 114  2006-09-13  - Whiskey in the morning,  mmmmmm, mmmmmmmmm, ...

 [115 rows x 2 columns]}

### Read data and append date columns

In [67]:
def append_date_columns(dataframe: pd.DataFrame):
    df = dataframe.copy()
    date_dict = { "year": [], "month": [], "day": [] }
    for date in df["date"].convert_dtypes():
        year, month, day = [None, None, None] if type(date) == pd._libs.missing.NAType else (date.split("-") + 3 * [None])[:3]
        date_dict["year"].append(year)
        date_dict["month"].append(month)
        date_dict["day"].append(day)
    for key in date_dict.keys():
        df[key] = date_dict[key]
    return df

# Append year, month and day columns. 
# This method insert None for undefined values

df = append_date_columns(dfs["William_Atchison"])
df

,date,text,year,month,day
0,NaN,"HOBBIES: Benzocaine, antidepressants, computer...",None,None,None
1,2009-09-11,1.I was immune to getting hurt/killed/infected...,2009,09,11
2,2009-09-11,I mean terrorist attacks happen all the time. ...,2009,09,11
3,2009-09-13,"As a god, it would be my responsibility not to...",2009,09,13
4,2009-09-13,I am going to grab a knife and shove it in the...,2009,09,13
...,...,...,...,...,...
264,2017-12-04,"Once I really am in power, my first and foremo...",2017,12,04
265,2017-12-05,Remember kids: If you plan on killing people d...,2017,12,05
266,2017-12-06,Praise be to allah,2017,12,06
267,2017-12-07,"If things go according to plan, today would be...",2017,12,07
268,2017-12-07,Die.,2017,12,07

### Concat all into one big dataframe

In [68]:
list_of_names = list(dfs.keys())
list_of_dfs = [append_date_columns(df).assign(Name=list_of_names[index].replace("_", " ")) for index, df in enumerate(dfs.values())]
df = pd.concat(list_of_dfs).reset_index()
df

,index,date,text,year,month,day,Name
0,0,NaN,Oh the happiness I could have had mingling amo...,None,None,None,Cho
1,1,NaN,Only if you could be the victim of your repreh...,None,None,None,Cho
2,2,NaN,"For every action, there is an equal and opposi...",None,None,None,Cho
3,3,NaN,"All the shit you’ve given me, right back at yo...",None,None,None,Cho
4,4,NaN,You had a hundred billion chances and ways to ...,None,None,None,Cho
...,...,...,...,...,...,...,...
437,110,2006-09-13,"- Hey girls, if you're feeling down, buy a ki...",2006,09,13,Kimveer Gill
438,111,2006-09-13,Frezzies - Freezies rock I'm eatting a purple...,2006,09,13,Kimveer Gill
439,112,2006-09-13,It's me :) - German Metal Yaaaaaaaaaaaaaa As...,2006,09,13,Kimveer Gill
440,113,2006-09-13,Wednessday the 13th - Woke up 30 minutes ago....,2006,09,13,Kimveer Gill
441,114,2006-09-13,"- Whiskey in the morning, mmmmmm, mmmmmmmmm, ...",2006,09,13,Kimveer Gill

### Some statistics

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   442 non-null    int64
 1   date    416 non-null    object
 2   text    438 non-null    object
 3   year    416 non-null    object
 4   month   367 non-null    object
 5   day     353 non-null    object
 6   Name    442 non-null    object
dtypes: int64(1), object(6)
memory usage: 24.3+ KB